services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=https://dawoonjung.com/api
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://dawoonjung.com/ws/messages
      - NEXT_PUBLIC_USER_ID=jdw-user-id
      - NEXT_PUBLIC_USER_CREATED_DATE=jdw-user-created-date
      - NEXT_PUBLIC_USER_IS_NEW=jdw-user-is-new
    env_file:
      - .env