services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/www/nginx/ssl:/etc/letsencrypt
      - /var/www/nginx/certbot:/var/www/certbot
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /var/www/nginx/ssl:/etc/letsencrypt
      - /var/www/nginx/certbot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email dawoonjung1026@gmail.com --agree-tos --no-eff-email -d dawoonjung.com -d www.dawoonjung.com

  frontend:
    build: .
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: yarn dev
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env